Link dataset LinkedIn : https://www.kaggle.com/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024

In [ ]:
import pandas as pd


df_job_posting = pd.read_csv("linkedin_job_postings.csv")
df_skills = pd.read_csv("job_skills.csv")
df_summary = pd.read_csv("job_summary.csv")

df_job_posting.head()
df_skills.head()
df_summary.head()

,job_link,job_summary
0,https://www.linkedin.com/jobs/view/restaurant-...,Rock N Roll Sushi is hiring a Restaurant Manag...
1,https://www.linkedin.com/jobs/view/med-surg-re...,Schedule\n: PRN is required minimum 12 hours p...
2,https://www.linkedin.com/jobs/view/registered-...,Description\nIntroduction\nAre you looking for...
3,https://uk.linkedin.com/jobs/view/commercial-a...,Commercial account executive\nSheffield\nFull ...
4,https://www.linkedin.com/jobs/view/store-manag...,Address:\nUSA-CT-Newington-44 Fenn Road\nStore...

In [6]:
df_summary.dropna(inplace=True)
df_job_posting.dropna(inplace=True)
df_skills.dropna(inplace=True)

df_merged = df_job_posting.merge(df_skills, on="job_link").merge(df_summary, on="job_link")
df_merged.head()

                                                                                                                   job_link  \
0  https://www.linkedin.com/jobs/view/account-executive-dispensing-norcal-northern-nevada-becton-dickinson-at-bd-3802078767
1                       https://www.linkedin.com/jobs/view/registered-nurse-rn-care-manager-at-trinity-health-mi-3803386312
2               https://www.linkedin.com/jobs/view/restaurant-supervisor-the-forklift-at-wasatch-adaptive-sports-3771464419
3                   https://www.linkedin.com/jobs/view/independent-real-estate-agent-at-howard-hanna-rand-realty-3797661348
4                                    https://www.linkedin.com/jobs/view/registered-nurse-rn-at-trinity-health-mi-3790954711

             last_processed_time got_summary got_ner is_being_worked  \
0   2024-01-21 07:12:29.00256+00           t       t               f
1   2024-01-21 07:39:58.88137+00           t       t               f
2  2024-01-21 07:40:00.251126+00           t       t               f
3  2024-01-21 07:40:00.308133+00           t       t               f
4  2024-01-21 08:08:19.663033+00           t       t               f

                                                                    job_title  \
0  Account Executive - Dispensing (NorCal/Northern Nevada) - Becton Dickinson
1                                          Registered Nurse - RN Care Manager
2                                        RESTAURANT SUPERVISOR - THE FORKLIFT
3                                               Independent Real Estate Agent
4                                                       Registered Nurse (RN)

                      company          job_location  first_seen  search_city  \
0                          BD         San Diego, CA  2024-01-15     Coronado
1           Trinity Health MI     Norton Shores, MI  2024-01-14  Grand Haven
2     Wasatch Adaptive Sports             Sandy, UT  2024-01-14       Tooele
3  Howard Hanna | Rand Realty  Englewood Cliffs, NJ  2024-01-16    Pinehurst
4           Trinity Health MI          Muskegon, MI  2024-01-14     Muskegon

  search_country           search_position   job_level job_type  \
0  United States               Color Maker  Mid senior   Onsite
1  United States  Director Nursing Service  Mid senior   Onsite
2  United States                  Stand-In  Mid senior   Onsite
3  United States         Real-Estate Clerk  Mid senior   Onsite
4  United States        Nurse Practitioner  Mid senior   Onsite

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            job_skills  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Medical equipment sales, Key competitors, Terminology, Technology, Trends, Challenges, Reimbursement, Government regulation, BD offerings, Pipeline management, Opportunity planning, Solution Sales Process, Customer relationships, Collaboration, Negotiation, Internal and external customer satisfaction, Trust building, Sales opportunities, New solution introduction, Pharmacy, IT, Nursing, Csuite, Bachelor's Degree, Travel, Driver's license
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Nursing, Bachelor of Science in Nursing, Masters Degree in Nursing, Care management experience, Clinical experience in nursing, Licensure to practice nursing in Michigan, Population management, Selfmanagement, Education, Oversight of registries, Patient education, Patient selfmanagement, Patient care coordination, Chronic condition management, Complex illness management, Hospitalization avoidance, Emergency room visit avoidance
2  Restaurant Operations Management, Inventory Management, Food and Beverage Ordering, Profit Optimization, Guest Service, Front and Back of House Coordination, Employee Performance Management, Discipline and Rewards Management, Safety and Sanitation Maintenance, Directional Flow Management, Daily Records Maintenance, Profit and Loss Statement Preparation, Guest Complaint Handling, Interpersonal Skills, Guest Service Skills, Listening Skills, Oral Communication Skills, Conflict Management Skills, Dispute Resolution Skills, Reading and Writing Proficiency, Arithmetic Skills, Menu and Wine List Knowledge, Wine Knowledge, Money Handling Proficiency, Staff Direction, Guest Issue Resolution, Microsoft Office Applications, Data Protection and Security, PCI DSS Compliance, Privacy and Confidentiality, Reporting and Storage of Sensitive Information, Snowbird Operations Knowledge, Variable Work Schedule, Overnight Stays, Stress Management, Physical Strength, Tray Carrying Ability, Standing Ability, Bending and Kneeling Ability, Repetitive Motions Ability, Professional Appearance, Drug and Alcohol Policy Compliance, Employee Conduct Policy Compliance
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Real Estate, Customer Service, Sales, Negotiation, Communication, Home Listings, Local Real Estate Market, Representation Contracts, Purchase Agreements, Closing Statements, Deeds, Leases, Networking, Relationship Building, Flexibility, Work/Life Balance, High Income Potential, Equal Opportunity Employer
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Nursing, BSN, Medical License, Virtual RN, Nursing Support, Diversity, Equity, Inclusion, Equal Opportunity Employer

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 job_summary
0  Responsibilities\nJob Description Summary\nJob Description\nWe are\nthe makers of possible\nBD is one of the largest global medical technology companies in the world. Advancing the world of health™ is our Purpose, and it’s no small feat. It takes the imagination and passion of all of us—from design and engineering to the manufacturing and marketing of our billions of MedTech products per year—to look at the impossible and find transformative solutions that turn dreams into possibilities.\nWe believe that the human element, across our global teams, is what allows us to continually evolve. Join us and discover an environment in which you’ll be supported to learn, grow and become your best self. Become a\nmaker of possible\nwith us.\nJob Title:\nAccount Executive- Acute Care\nTerritory:\nNorthern California, Northern Nevada - Must live in the geographical ar\nSummary\nThe Account Executive is responsible for driving sales and services to new and existing customers. They are responsible for maximizing customer value and satisfaction by aligning complex product solutions and services with key customer initiatives. Additional responsibilities include building and maintaining relationships with key decision makers or potential influencers; and managing a longer sales cycle.\nWhat is expected of you for success in your role\nDemonstrates advanced knowledge of BD and customer industry, including: key competitors, terminology, technology, trends, challenges, reimbursement and government regulation; demonstrates advance knowledge of how BD offerings match with customers' unique business needs.\nServes as a leader in maintaining balance in all areas of the pipeline, ensuring consistent sustainable results; manages pipeline independently within own business unit\nCreates and executes an opportunity plan independently which drives consistent results\nConsistently utilizes all resources available within own business unit and frequently involves other business units in consistently executing the Solution Sales Process\nWhat is expected of you and others at this level in Direct Sales\nApplies knowledge of the customer's business to develop optimal solutions\nProactively and with a regular cadence demonstrates to the customer the defined value of partnering with BD both pre- and post-sales\nEffectively negotiates and collaborates with the customer and colleagues to influence support for mutually beneficial outcomes and achieve consensus\nBuilds and sustains relationships founded on trust with internal and external customers and ensures customer satisfaction and loyalty\nIdentifies and qualifies new sales opportunities and develops plans for introducing new solutions through collaborative relationships\nQualifications\n2-3 years successful medical equipment sales (capital is preferred)\nPharmacy, IT, Nursing, C-suite call point\nAbility to manage a long sales cycle\nTravel up to 50% of the time\nBachelor’s Degree\nValid driver’s license\nMust live in territory\nFor certain roles at BD, employment is contingent upon the Company’s receipt of sufficient proof that you are fully vaccinated against COVID-19. In some locations, testing for COVID-19 may be available and/or required. Consistent with BD’s Workplace Accommodations Policy, requests for accommodation will be considered pursuant to applicable law.\nWhy Join Us?\nA career at BD means being part of a team that values your opinions and contributions and that encourages you to bring your authentic self to work. It’s also a place where we help each other be great, we do what’s right, we hold each other accountable, and learn and improve every day.\nTo find purpose in the possibilities, we need people who can see the bigger picture, who understand the human story that underpins everything we do. We welcome people with the imagination and drive to help us reinvent the future of health. At BD, you’ll discover a culture in which you can learn, grow, and thrive. And find satisfaction in doing your part to make the world a better place.\nTo learn more about BD visit  https://bd.com/careers\nBecton, Dickinson and Company is an Equal Opportunity/Affirmative Action Employer. We do not unlawfully discriminate on the basis of race, color, religion, age, sex, creed, national origin, ancestry, citizenship status, marital or domestic or civil union status, familial status, affectional or sexual orientation, gender identity or expression, genetics, disability, military eligibility or veteran status, or any other protected status.\nPDN\nPrimary Work Location\nUSA CA - San Diego Bldg A&B\nAdditional Locations\nWork Shift\nApply\nShow more\nShow less

In [8]:
df_merged_reduced = df_merged[["job_link", "job_title", "company", "job_location", "search_city","job_type", "search_position", "job_skills", "job_summary"]]
df_merged_reduced.to_csv("linkedin_job_postings_cleaned.csv", index=False)

In [9]:
# Save the first line of df_merged_reduced to a text file
first_line = df_merged_reduced.iloc[0]
first_line.to_string("first_line.txt")